#!/usr/bin/env bash
DIR="$(cd "$(dirname "$0")" && pwd)"

case "$(uname -s)" in
    Darwin)
        exec bash "$DIR/gh-codespace-windows-terminal.macos.sh" "$@"
        ;;
    *)
        exec pwsh.exe -NoLogo -NoProfile -File "$DIR/gh-codespace-windows-terminal.ps1" "$@"
        ;;
esac